### ISSUE TITLE
Send Many Nfts  一直发送失败，链上错误代码402

### ISSUE THREAD

**Issue by Mountain-AI** [TrueCarry/ton-collection-edit#4]
NFT item地址：https://testnet.tonviewer.com/EQD2pCECGi3-FbFZrjduHFvWOefugb1Uw1gJV0SCTzEN0i6A
这个collection和nfts都是通过网站部署的，但是批量转移NFT时失败，通过查看交易详情可以看到错误代码402
![1715744794588](https://github.com/TrueCarry/ton-collection-edit/assets/40032239/941a5f7f-6899-4207-9e0e-efa127fa0a46)

下面是源码中402的出处可以参考
![photo_2024-05-15_10-38-59](https://github.com/TrueCarry/ton-collection-edit/assets/40032239/722557d7-030d-4357-9dc5-1537da45604d)

**Comment by Mountain-AI** [comment]
![1715768213057](https://github.com/TrueCarry/ton-collection-edit/assets/40032239/dfc5c6b2-0905-4853-981d-26314b5e74f0)
本地运行，修改了下这个，可以正常批量转nft，不错数量不能超过4个
![1715768637530](https://github.com/TrueCarry/ton-collection-edit/assets/40032239/083024b3-0931-4cce-b9ad-07eb820880c6)

**Comment by TrueCarry** [comment]
![image](https://github.com/TrueCarry/ton-collection-edit/assets/5431520/9a5d1ee7-2fab-402d-acb6-8827363bf0f4)
I've added input, so you can change amount of TON sent with transfer. Set it to 0.1 TON and it should work.
