### ISSUE TITLE
missisue edit nft sale price cannot be canceled

### ISSUE THREAD

**Issue by obengsub** [TrueCarry/ton-collection-edit#5]
after edit sale price, i had encountered problem after send tx.
the collection is enabled hide list custom.
- transaction on tonviewer: [tonviewer](https://tonviewer.com/transaction/7f2bdefddcf72a39aee7d5dc1c56efaa82e74e444bd5da5872c4088f7e6edc7d)
- Recipent on tonkeeper: `EQDPfNpOWGcLn6gCafnFB5-7uBss7MMncP0Nuug2OSEzLNwz`
- Payload: `0x6c6c2080`
- NFT Address: `EQD3FKDSiB-ITh93-D3Q8AIiDL_ZiMVmIJG-CJVZLlE5BCK7` or [getgems](https://getgems.io/nft/EQD3FKDSiB-ITh93-D3Q8AIiDL_ZiMVmIJG-CJVZLlE5BCK7) and [tonex](https://tonex.app/@EQAxnOWAZEjqWjAU5QalNmWclkb7_l-A6hPFET2wzMRNV05B/nfts/EQD3FKDSiB-ITh93-D3Q8AIiDL_ZiMVmIJG-CJVZLlE5BCK7)

now i cannot put on sale and cancel on my side.
thanks in advance for new feature

**Comment by TrueCarry** [comment]
What's your proposal to fix that? I think not setting fees to 0 should help, you have inputs for that.
